# Generated by Django 6.0.4 on 2026-04-16 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vazifa2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('yangi', 'Yangi'), ('jarayonda', 'Jarayonda'), ('tugadi', 'Tugadi')], default='yangi', max_length=20)),
            ],
        ),
    ]
